server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/aishop_db}
    username: ${SPRING_DATASOURCE_USERNAME:aishop_user}
    password: ${SPRING_DATASOURCE_PASSWORD:aishop1234}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  thymeleaf:
    cache: false

logging:
  level:
    org.hibernate.SQL: debug
